name: CI/CD Pipeline for YOLO API

on:
  push:

jobs:
  build-and-deploy-yolo:
    runs-on: ubuntu-latest  # 우분투 환경에서 실행

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. ECR 로그인
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 3. YOLO API 이미지 빌드 및 ECR에 푸시
      - name: Build, tag, and push YOLO image
        env:
          ECR_REGISTRY: <YOUR_ECR_REGISTRY>  # ECR 레지스트리 주소
          ECR_REPOSITORY: labeling-yolo      # YOLO API ECR 리포지토리 이름
          IMAGE_TAG: latest                  # 이미지 태그
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./yolo-api  # YOLO API 이미지 빌드
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG  # ECR에 YOLO 이미지 푸시

      # 4. ECS 서비스 업데이트 (YOLO API)
      - name: Update ECS Service for YOLO API
        env:
          CLUSTER_NAME: <YOUR_ECS_CLUSTER>       # ECS 클러스터 이름
          SERVICE_NAME: yolo-service             # YOLO 서비스 이름
          CONTAINER_NAME: yolo-container         # YOLO 컨테이너 이름
        run: |
          aws ecs update-service \
            --cluster $CLUSTER_NAME \
            --service $SERVICE_NAME \
            --force-new-deployment  # YOLO API 컨테이너 강제 배포
